############################### REGULAR EXPeresion #############################################
Email_REGEX = /^[A-Z0-9._%+-]+@(?:[A-Z0-9-]+\.)+[A-Z]{2,4}$/i  

REGX_PHONE_NUMBER = /^(\+44)?\s?\(?0\)?[12358]\d\s?\d\)?\s?\d\)?(\s?\d){6}|^(\+44)?\s?\(?0\)?7[5789]\d\s?\d\)?\s?\d\)?(\s?\d){5}$/
REGX_MOBILE = /^(\+44)?\s?\(?0\)?7[5789]\d\s?\d\)?\s?\d\)?(\s?\d){5}$/
REGX_LANDLINE = /^(\+44)?\s?\(?0\)?[12358]\d\s?\d\)?\s?\d\)?(\s?\d){6}$/

REGX_POSTCODE = /(^[A-Z]{1,2}[0-9]{1,2})([0-9][A-Z]{2}$)/i
REGX_COMPANY_SUBDOMAIN = /^[a-z\d]+(-[a-z\d]+)*$/i

    #--- User ---#
USER_STATUS_PENDING = "pending"
USER_STATUS_ACTIVE = "active"
USER_STATUS_INACTIVE = "inactive"
USER_STATUS_DELETED = "deleted"

USER_STATUS_LIST = [USER_STATUS_PENDING, USER_STATUS_ACTIVE, USER_STATUS_INACTIVE, USER_STATUS_DELETED]

USER_TYPE_CONTACT = "contact"
USER_TYPE_STAFF = "staff"
CONTACT_TYPE_CLIENT_CONTACT = "client contact"
CONTACT_TYPE_CANDIDATE = "candidate"


    #--- System settings ---#
SETTING_TYPE_INT = "int"
SETTING_TYPE_TEXT = "text"
SETTING_TYPE_LONGTEXT = "longtext"
SETTING_TYPE_HTML = "html"
SETTING_TYPE_EMAIL = "email"
SETTING_TYPE_ARRAY = "array"

SETTING_TYPE_LIST = [ SETTING_TYPE_INT, SETTING_TYPE_TEXT, SETTING_TYPE_LONGTEXT, SETTING_TYPE_HTML, SETTING_TYPE_EMAIL, SETTING_TYPE_ARRAY ]



    #--- Company ---#
COMPANY_STATUS_UNCONFIRMED = "unconfirmed"
COMPANY_STATUS_ACTIVE = "active"
COMPANY_STATUS_CLIENT = "client"
COMPANY_STATUS_DELETED = "deleted"

COMPANY_STATUS_LIST = {COMPANY_STATUS_UNCONFIRMED => COMPANY_STATUS_UNCONFIRMED.titleize, COMPANY_STATUS_ACTIVE => COMPANY_STATUS_ACTIVE.titleize, COMPANY_STATUS_CLIENT => COMPANY_STATUS_CLIENT.titleize, COMPANY_STATUS_DELETED => COMPANY_STATUS_DELETED.titleize}

COMPANY_OVERVIEW = "overview"
COMPANY_CAMPAIGNS = "campaigns"
COMPANY_CONTACTS = "contacts"
COMPANY_WHITELABELING = "whitelabeling"
COMPANY_CONTACT_LOG = "contact log"

COMPANY_PROFILE_SECTIONS = {COMPANY_OVERVIEW => COMPANY_OVERVIEW.titleize, COMPANY_CAMPAIGNS => COMPANY_CAMPAIGNS.titleize, COMPANY_CONTACTS => COMPANY_CONTACTS.titleize, COMPANY_WHITELABELING => COMPANY_WHITELABELING.titleize, COMPANY_CONTACT_LOG => COMPANY_CONTACT_LOG.titleize}


CANDIDATE_OVERVIEW = "overview"
CANDIDATE_PROFILE = "candidate profile"
CANDIDATE_TRAITS = "traits"
CANDIDATE_QUALIFICATION = "qualifications"
CANDIDATE_CONTACT_LOG = "contact log"
CANDIDATE_CAMPAIGNS = "campaigns"
CANDIDATE_INTERVIEWS = "interviews"
CANDIDATE_EXAMS = "exams"

CONTACT_PROFILE_SECTIONS = [CANDIDATE_OVERVIEW, CANDIDATE_PROFILE, CANDIDATE_TRAITS, CANDIDATE_QUALIFICATION, CANDIDATE_CONTACT_LOG, CANDIDATE_CAMPAIGNS, CANDIDATE_INTERVIEWS, CANDIDATE_EXAMS]




    #--- Campaign ---#
CAMPAIGN_STATUS_DRAFT = "draft"
CAMPAIGN_STATUS_ACTIVE = "active"
CAMPAIGN_STATUS_INACTIVE = "inactive"
CAMPAIGN_STATUS_DELETED = "deleted"

CAMPAIGN_STATUS_LIST = [ CAMPAIGN_STATUS_DRAFT, CAMPAIGN_STATUS_ACTIVE, CAMPAIGN_STATUS_INACTIVE, CAMPAIGN_STATUS_DELETED ]



    #--- UserCampaign ---#
USER_CAMPAIGN_STATUS_APPLIED = "applied"    
USER_CAMPAIGN_STATUS_PENDING = "pending"
USER_CAMPAIGN_STATUS_INITIAL = "initial"
USER_CAMPAIGN_STATUS_ADDITIONAL = "additional"
USER_CAMPAIGN_STATUS_PHONE = "phone"
USER_CAMPAIGN_STATUS_VERIFICATION = "verification"
USER_CAMPAIGN_STATUS_INTERVIEW = "interview"
USER_CAMPAIGN_STATUS_FORWARDED = "forwarded"
USER_CAMPAIGN_STATUS_REJECTED = "rejected"
USER_CAMPAIGN_STATUS_ACCEPTED = "accepted"

USER_CAMPAIGN_STATUS_LIST = [ USER_CAMPAIGN_STATUS_PENDING, USER_CAMPAIGN_STATUS_INITIAL, USER_CAMPAIGN_STATUS_ADDITIONAL, USER_CAMPAIGN_STATUS_PHONE, USER_CAMPAIGN_STATUS_VERIFICATION, USER_CAMPAIGN_STATUS_INTERVIEW, USER_CAMPAIGN_STATUS_FORWARDED, USER_CAMPAIGN_STATUS_REJECTED, USER_CAMPAIGN_STATUS_ACCEPTED ]
PHONE_RESULT_LIST = ["pass", "fail"]
INTERVIEW_RESULT_LIST = ["pass", "fail"]



    #--- Note ---#
TABLE_COMPANIES = "companies"    



    #--- ContactLog ---#
CONTACT_LOG_METHOD_PHONE = "phone"
CONTACT_LOG_METHOD_EMAIL = "email"
CONTACT_LOG_METHOD_FAX = "fax"
CONTACT_LOG_METHOD_SMS = "sms"
CONTACT_LOG_METHOD_POST = "post"

CONTACT_LOG_METHOD_LIST = {CONTACT_LOG_METHOD_PHONE => CONTACT_LOG_METHOD_PHONE.titleize, CONTACT_LOG_METHOD_EMAIL => CONTACT_LOG_METHOD_EMAIL.titleize, CONTACT_LOG_METHOD_FAX => CONTACT_LOG_METHOD_FAX.titleize, CONTACT_LOG_METHOD_SMS => CONTACT_LOG_METHOD_SMS.titleize, CONTACT_LOG_METHOD_POST => CONTACT_LOG_METHOD_POST.titleize}



    #--- Static Data ---#
COUNTRY_LIST = ["UK", "US"]     #TODO: 


    
    
####################QUALIFICATION TYPE########################################
QUALIFICATION_STATUS_UNCONFIRMED = "unconfirmed"
QUALIFICATION_STATUS_ACTIVE = "active"
QUALIFICATION_STATUS_DELETED = "deleted"

QUALIFICATION_STATUS_LIST = {QUALIFICATION_STATUS_UNCONFIRMED => QUALIFICATION_STATUS_UNCONFIRMED.titleize, QUALIFICATION_STATUS_ACTIVE => QUALIFICATION_STATUS_ACTIVE.titleize, QUALIFICATION_STATUS_DELETED => QUALIFICATION_STATUS_DELETED.titleize}

####################QUALIFICATION LOCATION####################################
QUALIFICATION_LOCATION_STATUS_UNCONFIRMED = "unconfirmed"
QUALIFICATION_LOCATION_STATUS_ACTIVE = "active"
QUALIFICATION_LOCATION_STATUS_DELETED = "deleted"

QUALIFICATION_LOCATION_STATUS_LIST = {QUALIFICATION_LOCATION_STATUS_UNCONFIRMED => QUALIFICATION_LOCATION_STATUS_UNCONFIRMED.titleize, QUALIFICATION_LOCATION_STATUS_ACTIVE => QUALIFICATION_LOCATION_STATUS_ACTIVE.titleize, QUALIFICATION_LOCATION_STATUS_DELETED => QUALIFICATION_LOCATION_STATUS_DELETED.titleize}

####################QUALIFICATION SUBJECT#####################################
QUALIFICATION_SUBJECT_STATUS_UNCONFIRMED = "unconfirmed"
QUALIFICATION_SUBJECT_STATUS_ACTIVE = "active"
QUALIFICATION_SUBJECT_STATUS_DELETED = "deleted"

QUALIFICATION_SUBJECT_STATUS_LIST = {QUALIFICATION_SUBJECT_STATUS_UNCONFIRMED => QUALIFICATION_SUBJECT_STATUS_UNCONFIRMED.titleize, QUALIFICATION_SUBJECT_STATUS_ACTIVE => QUALIFICATION_SUBJECT_STATUS_ACTIVE.titleize, QUALIFICATION_SUBJECT_STATUS_DELETED => QUALIFICATION_SUBJECT_STATUS_DELETED.titleize}

####################QUALIFICATION##################################################

QUALIFICATION_GRADE_STATUS_UNCONFIRMED = "unconfirmed"
QUALIFICATION_GRADE_STATUS_ACTIVE = "active"
QUALIFICATION_GRADE_STATUS_DELETED = "deleted"
QUALIFICATION_GRADE_STATUS_LIST = {QUALIFICATION_GRADE_STATUS_UNCONFIRMED => QUALIFICATION_GRADE_STATUS_UNCONFIRMED.titleize, QUALIFICATION_GRADE_STATUS_ACTIVE => QUALIFICATION_GRADE_STATUS_ACTIVE.titleize, QUALIFICATION_GRADE_STATUS_DELETED => QUALIFICATION_GRADE_STATUS_DELETED.titleize}

QUESTION_CATEGORY_STATUS_ACTIVE = 'active'
QUESTION_CATEGORY_STATUS_DELETED = 'deleted'
QUESTION_CATEGORY_STATUS_LIST = {QUESTION_CATEGORY_STATUS_ACTIVE => QUESTION_CATEGORY_STATUS_ACTIVE.titleize, QUESTION_CATEGORY_STATUS_DELETED => QUESTION_CATEGORY_STATUS_DELETED.titleize}

####################TRAIT####################################################
TRAIT_STATUS_INTERNAL = "internal"
TRAIT_STATUS_PUBLIC = "public"
TRAIT_STATUS_DELETED = "deleted"
TRAIT_STATUS_LIST = {TRAIT_STATUS_INTERNAL => TRAIT_STATUS_INTERNAL.titleize, TRAIT_STATUS_PUBLIC => TRAIT_STATUS_PUBLIC.titleize, TRAIT_STATUS_DELETED => TRAIT_STATUS_DELETED.titleize}

####################LANGUAGE#################################################
LANGUAGE_STATUS_UNCONFIRMED = "unconfirmed"
LANGUAGE_STATUS_ACTIVE = "active"
LANGUAGE_STATUS_DELETED = "deleted"
LANGUAGE_STATUS_LIST = {LANGUAGE_STATUS_UNCONFIRMED => LANGUAGE_STATUS_UNCONFIRMED.titleize, LANGUAGE_STATUS_ACTIVE => LANGUAGE_STATUS_ACTIVE.titleize, LANGUAGE_STATUS_DELETED => LANGUAGE_STATUS_DELETED.titleize}

LANGUAGE_LEVEL_BASIC = "basic"
LANGUAGE_LEVEL_INTERMEDIATE = "intermediate"
LANGUAGE_LEVEL_ADVANCED = "advanced"
LANGUAGE_LEVEL_LIST = [LANGUAGE_LEVEL_BASIC, LANGUAGE_LEVEL_INTERMEDIATE, LANGUAGE_LEVEL_ADVANCED]

####################SKILL###################################################
SKILL_LEVEL_BASIC = "basic"
SKILL_LEVEL_INTERMEDIATE = "intermediate" 
SKILL_LEVEL_ADVANCED = "advanced" 
SKILL_LEVEL_LIST = [ SKILL_LEVEL_BASIC, SKILL_LEVEL_INTERMEDIATE , SKILL_LEVEL_ADVANCED ]

IT_SKILL_STATUS_UNCONFIRMED = "unconfirmed"
IT_SKILL_STATUS_ACTIVE = "active"
IT_SKILL_STATUS_DELETED = "deleted"
IT_SKILL_STATUS_LIST = {IT_SKILL_STATUS_UNCONFIRMED => IT_SKILL_STATUS_UNCONFIRMED.titleize, IT_SKILL_STATUS_ACTIVE => IT_SKILL_STATUS_ACTIVE.titleize, IT_SKILL_STATUS_DELETED => IT_SKILL_STATUS_DELETED.titleize}


FILE_TYPE_CV = "cv"
FILE_TYPE_IMAGE = "image"
FILE_TYPE_OTHER = "other"
FILE_TYPE_LIST = [ FILE_TYPE_CV, FILE_TYPE_OTHER ]
FILE_SIZE_MAX_20MB = 20.megabytes
FILE_SIZE_MAX_10MB = 10.megabytes
FILE_CV_SUPPORTED_FORMATS = "doc docx pdf rtf"
FILE_IMAGE_SUPPORTED_FORMATS = "jpg jpeg pdf tiff gif bmp png"


########QUESTION##################

QUESTION_STATUS_ACTIVE = 'active'
QUESTION_STATUS_DELETED = 'deleted'
QUESTION_STATUS = {
  QUESTION_STATUS_ACTIVE => 'Active',
  QUESTION_STATUS_DELETED => 'Deleted'
}


QUESTION_PART_TYPE_MULTIPLE = "multiple"
QUESTION_PART_TYPE_SELECT = "select"
QUESTION_PART_TYPE_TEXT = "text"

QUESTION_PART_TYPE = {
  QUESTION_PART_TYPE_MULTIPLE => "multiple",
  QUESTION_PART_TYPE_SELECT => "select",
  QUESTION_PART_TYPE_TEXT => "text"
}

DIFFICULTY_LEVEL_EASY = 'easy'
DIFFICULTY_LEVEL_MEDIUM = 'medium'
DIFFICULTY_LEVEL_HARD = 'hard'

DIFFICULTY_LEVEL = {
  DIFFICULTY_LEVEL_EASY => 'easy',
  DIFFICULTY_LEVEL_MEDIUM => 'medium',
  DIFFICULTY_LEVEL_HARD => 'hard'
}

########EXAMS##################
EXAM_STATUS_DRAFT = 'draft'
EXAM_STATUS_ACTIVE = 'active'
EXAM_STATUS_INACTIVE = 'inactive'
EXAM_STATUS_DELETED = 'deleted'
EXAM_STATUS = {
  EXAM_STATUS_DRAFT => 'Draft',
  EXAM_STATUS_ACTIVE => 'Active',
  EXAM_STATUS_INACTIVE => 'Inactive',
  EXAM_STATUS_DELETED => 'Deleted'
}



##################### INTERVIEW TYPE #############################################################
INTERVIEW_TYPE_PHONE = "phone"
INTERVIEW_TYPE_FACETOFACE = "face to face"

INTERVIEW_TYPE_LIST = [INTERVIEW_TYPE_PHONE, INTERVIEW_TYPE_FACETOFACE]
##################################################################################################


NOT_AVAILABLE = "N/A"

#==============================Exam Type =========================================================
EXAM_STAGE_INITIAL = "initial"
EXAM_STAGE_ADDITIONAL = "additional"
EXAM_STAGE_VERIFICATION = "verification"

#==============================UserExam Status ====================================================
USER_EXAM_PENDING = "pending"
USER_EXAM_STARTED = "started"
USER_EXAM_ENDED = "ended"

#==================================================================================================

CONTACT_UNEMPLOYED = "Unemployed"
